# Generated by Django 4.0.4 on 2022-04-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lat', models.DecimalField(decimal_places=5, default=None, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=5, default=None, max_digits=8)),
            ],
        ),
    ]
