# Generated by Django 4.0.4 on 2022-04-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interest', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('username', models.CharField(default=None, max_length=25, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=350)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('DOB', models.DateField()),
                ('date_joined', models.DateField(auto_now=True)),
                ('is_social', models.BooleanField(default=False)),
                ('is_work', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('in relationship', 'In Relationship'), ('engaged', 'Engaged'), ('married', 'Married')], default=('single', 'Single'), max_length=20)),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('employed', 'Employed'), ('self employed', 'Self Employed'), ('unemployed', 'Unemployed'), ('freelancer', 'Freelancer')], max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
                ('interests', models.ManyToManyField(default=None, null=True, to='interest.interest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
    ]
