# Generated by Django 4.0.4 on 2022-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.JSONField(default={'School': None, 'end_date': None, 'start_date': None}),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.JSONField(default={'Role': None, 'Workplace': None, 'end_date': None, 'start_date': None}),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(null=True, to='interest.interest'),
        ),
    ]
