# Generated by Django 4.0.4 on 2022-04-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_education_userprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.JSONField(default={'School': None, 'certification': None, 'end_date': None, 'start_date': None}),
        ),
    ]
