# Generated by Django 4.0.4 on 2022-04-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('interest', '0001_initial'),
        ('accounts', '0006_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='interest.interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('in relationship', 'In Relationship'), ('engaged', 'Engaged'), ('married', 'Married')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employed', 'Employed'), ('self employed', 'Self Employed'), ('unemployed', 'Unemployed'), ('freelancer', 'Freelancer')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
