# Generated by Django 4.0.4 on 2022-04-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_address_user_education_user_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_social',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_work',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('social', 'Social'), ('work', 'Work'), ('both', 'Both')], max_length=6),
        ),
    ]
